moncampus_username: Votre nom d'utilisateur MonCampus  
moncampus_password: Votre mot de passe MonCampus  
moncampus_start_date: Date de début (AAAA-MM-JJ) pour récupérer les événements MonCampus  
moncampus_end_date: Date de fin (AAAA-MM-JJ) pour récupérer les événements MonCampus  
ecal_api_key: Votre clé API ecal.com  
ecal_api_secret: Votre clé secrète API ecal.com  
ecal_calendar_id: L'ID de votre calendrier sur ecal.com  
error_file_path: /app/errors.txt 