services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moncampusecal
    depends_on:
      - selenium
    networks:
      - selenium_network
    restart: always

  selenium:
    image: selenium/standalone-firefox:4.27.0
    environment:
      - SE_NODE_HOST=localhost
      - SE_NODE_PORT=5555
      - SE_ENABLE_TRACING=false
    ports:
      - "4444:4444"
    networks:
      - selenium_network
networks:
  selenium_network:
    driver: bridge
