services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moncampusecal
    depends_on:
      - chrome
    networks:
      - selenium_network
    restart: always

  chrome:
    image: selenium/node-chrome:4.0.0-rc-1-prerelease-20210823
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    networks:
      - selenium_network
    platform: linux/arm64

  selenium-hub:
    image: selenium/hub:4.0.0-rc-1-prerelease-20210823
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium_network
    platform: linux/arm64

networks:
  selenium_network:
    driver: bridge
